title: "kellyling Blog"
languageCode: "zh-CN"
baseurl: "https://kellyling.github.io"
copyright: "Copyright (c) 2017. All rights reserved</a>"
theme: "hugo-rapid-theme"
MetaDataFormat: "yaml"
canonifyurls: true
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "default"
pygmentsUseClasses: true
RSSUri: "feed.xml"
disablePathToLower: true 
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:slug/

Taxonomies:
  tag: "tags"
  category: "categories"

params:
  GitHubUser: "coderzh"
  SidebarRecentLimit: 5
  DateForm : "2006年01月02日"
  Tagline: ""
  Description: ""
  Keywords: "独立博客,程序员,思考,读书笔记,技术分享"
  Categories:
    - "学习笔记"
    - "技术分享"
    - "其他内容"
menu:
  main:
      - Name: "归档"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
author:
  name: "kellyling"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
